name: Bubble
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.2.0
  # Localization https://github.com/dart-lang/intl
  intl: ^0.18.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.3.2
  # 网络库 https://github.com/cfug/dio
  dio: ^5.3.3
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.7
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.1.0
  sp_util: 2.0.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars_flutter3: ^3.0.0 # flustars很久不维护，可以使用这个替代
  # Flutter 轮播图 https://github.com/mdddj/flutter_swiper_null_safety
  flutter_swiper_null_safety_flutter3: ^4.0.0   # flutter_swiper很久不维护，可以使用这个替代
  # 启动URL的插件（支持Web） https://github.com/flutter/packages/tree/main/packages/url_launcher
  url_launcher: 6.1.8
  # 图片选择插件 https://github.com/flutter/packages/tree/main/packages/image_picker
  image_picker: 1.0.4
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^3.0.0
  # WebView插件 https://github.com/flutter/packages/tree/main/packages/webview_flutter
  webview_flutter: 4.2.4
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^4.2.0
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^2.0.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.5
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.3.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^7.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^6.0.5
  # 扫码 https://github.com/juliuscanute/qr_code_scanner
  qr_code_scanner: 1.0.0
  #    git:
  #      url: https://github.com/xeinebiu/qr_code_scanner.git
  #      ref: fix_break_changes_platform
  # App Shortcuts https://github.com/flutter/packages/tree/main/packages/quick_actions
  quick_actions: 1.0.5
  # 振动 https://github.com/benjamindean/flutter_vibration
  vibration: 1.8.1
  vibration_web: 1.6.5
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 9.0.2
  package_info: ^2.0.2

  # 动画效果 https://github.com/xvrh/lottie-flutter
  lottie: ^2.6.0
  #进度条
  percent_indicator: ^4.0.1
  # websocket https://github.com/dart-lang/web_socket_channel
  web_socket_channel: ^2.4.0
  # flutter_sound https://github.com/canardoux/flutter_sound
  flutter_sound: ^9.2.13
  # uuid https://github.com/Daegalus/dart-uuid
  uuid: ^3.0.7
  # permission_handler https://github.com/baseflow/flutter-permission-handler
  permission_handler: ^11.0.1
  #crypto: ^3.0.3 https://github.com/dart-lang/crypto
  crypto: ^3.0.3
  #xml2json: ^6.2.1 https://github.com/shamblett/xml2json
  xml2json: ^6.2.1
  #start
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/state/

  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
